### ISSUE TITLE
Clarification for: Jumping to next field gets to one character before next field

### ISSUE THREAD

**Issue by SKlimaszewskiFDX** [shriprem/FWDataViz#82] opened 2022-10-26 13:02 UTC
Clicking on ">" button to jump to next field makes it jump to one char before the actual field. ("<" button works well for example).

![image](https://user-images.githubusercontent.com/116731096/198032753-69c82c5f-867f-4b43-bdbf-21b9e1952add.png)

**Comment by shriprem** [comment] 2022-10-29 05:05
[_As chance would have it, I was on a long flight when you reported this bug. Hence the delay in my response here._]

This is an intended feature, not a bug. The buttons you are referring to are for the **Hop Field** feature, although they are not labeled as such on the controls for UI brevity. The fact that they are placed on either side of the **Jump to Field** button may have been the source for you confusion.

Please refer to the [documentation for the **Hop Field** controls](https://github.com/shriprem/FWDataViz/blob/master/docs/field_navigation.md#jump-to-field). Especially, see the highlighted text in the screenshot below from that page.

![image](https://user-images.githubusercontent.com/45252729/198814805-213af93e-d6af-4f5a-8ae0-aacd5cffb7d7.png)

Additionally, if you hover the mouse over the **Hop Field** buttons in the plugin panel, you will see the exact information in the balloon text.

I think this clarification is sufficient to close this issue.

**Closed by shriprem** 2022-10-29 05:05 UTC
Labels: documentation

**Comment by shriprem** [comment] 2023-08-05 01:37
The issue you raised was also put forth by another user recently. See: #86. So, I have implemented a customizable setting for the right hop action.

Here is the Preferences screen, with the customizable option for 'Hop Right':
![image](https://github.com/shriprem/FWDataViz/assets/45252729/e9419ab5-fbec-449d-b4f6-e6786f9a46d8)

1. First, you will need the plugin DLL from the latest commit [CI build](https://github.com/shriprem/FWDataViz/actions/workflows/CI_build.yml). On the CI Builds page, click on the link for the top (recent) workflow run. Here is the current [direct link](https://github.com/shriprem/FWDataViz/actions/runs/5766732801). This page will have zipped DLLs for x64, x86 & ARM64. For more info on installing the DLL, see: [Downloading FWDataViz.dll file from a commit to the Github repo](https://github.com/shriprem/FWDataViz/discussions/73).
2. For the hop behavior that you are looking to have, you will need to check the box for 'Hop Right...' For more details, see: [Hop Right](https://github.com/shriprem/FWDataViz/blob/master/docs/field_navigation.md#hop-field)
